#!/usr/bin/env bash
set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
home_dir="${HOME:?HOME is not set}"
config_home="${XDG_CONFIG_HOME:-$home_dir/.config}"
setup_dir="$config_home/coding-agent-setups"
flag_file="${CODING_AGENT_SETUPS_FLAG_FILE:-$setup_dir/sync.env}"
opencode_env="$home_dir/.config/opencode/.env"

read_existing_key() {
  local file="$1"
  local key="$2"
  if [[ -f "$file" ]]; then
    awk -F= -v key="$key" '$1 == key { sub(/^[^=]*=/, ""); print; exit }' "$file"
  fi
}

existing_yes_no() {
  local key="$1"
  local fallback="$2"
  local current
  current="$(read_existing_key "$flag_file" "$key")"
  case "${current,,}" in
    1|true|yes|on) printf 'y' ;;
    0|false|no|off) printf 'n' ;;
    *) printf '%s' "$fallback" ;;
  esac
}

prompt_yes_no() {
  local prompt="$1"
  local default_value="$2"
  local suffix answer

  case "$default_value" in
    y) suffix="Y/n" ;;
    n) suffix="y/N" ;;
    *) suffix="y/n" ;;
  esac

  while true; do
    read -r -p "$prompt [$suffix]: " answer
    answer="${answer:-$default_value}"
    case "${answer,,}" in
      y|yes) printf '1'; return 0 ;;
      n|no) printf '0'; return 0 ;;
      *) echo "Please answer yes or no." >&2 ;;
    esac
  done
}

prompt_value() {
  local file="$1"
  local key="$2"
  local prompt="$3"
  local default_value="${4:-}"
  local current value

  current="$(read_existing_key "$file" "$key")"
  if [[ -n "$current" ]]; then
    default_value="$current"
  fi

  if [[ -n "$default_value" ]]; then
    read -r -p "$prompt [$default_value]: " value
    value="${value:-$default_value}"
  else
    while [[ -z "${value:-}" ]]; do
      read -r -p "$prompt: " value
    done
  fi
  printf '%s' "$value"
}

prompt_secret() {
  local file="$1"
  local key="$2"
  local prompt="$3"
  local current value

  current="$(read_existing_key "$file" "$key")"
  if [[ -n "$current" ]]; then
    read -r -s -p "$prompt [keep existing]: " value
    echo
    value="${value:-$current}"
  else
    while [[ -z "${value:-}" ]]; do
      read -r -s -p "$prompt: " value
      echo
    done
  fi
  printf '%s' "$value"
}

set_env_var() {
  local file="$1"
  local key="$2"
  local value="$3"
  local tmp

  mkdir -p "$(dirname "$file")"
  touch "$file"
  chmod 600 "$file"
  tmp="$(mktemp)"
  awk -v key="$key" -v value="$value" '
    BEGIN { done = 0 }
    $0 ~ "^" key "=" {
      print key "=" value
      done = 1
      next
    }
    { print }
    END {
      if (done == 0) {
        print key "=" value
      }
    }
  ' "$file" > "$tmp"
  mv "$tmp" "$file"
  chmod 600 "$file"
}

write_flags() {
  local codex="$1"
  local claude="$2"
  local opencode="$3"
  local tmp

  mkdir -p "$setup_dir"
  tmp="$(mktemp)"
  cat > "$tmp" <<EOF
# Generated by coding-agent-setups/scripts/setup.sh.
# This file is machine-local and controls what scripts/sync.sh copies.
SYNC_CODEX=$codex
SYNC_CLAUDE=$claude
SYNC_OPENCODE=$opencode
EOF
  mv "$tmp" "$flag_file"
  chmod 600 "$flag_file"
}

echo "Shared agent files are always installed."

sync_codex="$(prompt_yes_no "Sync Codex setup on this machine?" "$(existing_yes_no SYNC_CODEX y)")"
sync_claude="$(prompt_yes_no "Sync Claude Code setup on this machine?" "$(existing_yes_no SYNC_CLAUDE y)")"
sync_opencode="$(prompt_yes_no "Sync OpenCode setup on this machine?" "$(existing_yes_no SYNC_OPENCODE y)")"

if [[ "$sync_opencode" == "1" ]]; then
  echo "Configuring local OpenCode environment."
  base_url="$(prompt_value "$opencode_env" OPENCODE_LITELLM_BASE_URL "LiteLLM base URL" "http://localhost:4000/v1")"
  api_key="$(prompt_secret "$opencode_env" OPENCODE_LITELLM_API_KEY "LiteLLM API key")"

  set_env_var "$opencode_env" OPENCODE_LITELLM_BASE_URL "$base_url"
  set_env_var "$opencode_env" OPENCODE_LITELLM_API_KEY "$api_key"
  set_env_var "$opencode_env" OPENCODE_ENABLE_EXA "1"
  set_env_var "$opencode_env" OPENCODE_EXPERIMENTAL_BACKGROUND_SUBAGENTS "1"
fi

write_flags "$sync_codex" "$sync_claude" "$sync_opencode"
echo "Wrote sync selection to $flag_file"

bash "$repo_root/scripts/sync.sh" --to-home

echo "Setup complete. OAuth files are not synced; run each enabled agent's login flow on this machine."

